
name: Weekly Legislation & Policy Update

on:
  schedule:
    # Runs at 08:00 UTC every Tuesday
    - cron: '0 8 * * 2'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Update Script
        run: npm run update-data

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'KenyaYetu Bot'
          git config --global user.email 'bot@kenyayetu.co.ke'
          # Updated to include data/legislation/county-laws.ts
          git add data/legislation/acts.ts data/knowledge-base/national-policies.ts data/legislation/county-laws.ts data/knowledge-base/county-policies.ts
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Automated Data Update: New Laws/Policies found" && git push)
